/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/viking.glb 
Author: Andy Woodhead (https://sketchfab.com/Andywoodhead)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/viking-helmet-free-download-0030d8b91c414b619f2ca3ae79e7a080
Title: Viking Helmet - free download
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/viking.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Liner} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.Mail} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.Mail} />
          <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.Face_guard} />
          <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials.Face_guard} />
          <mesh geometry={nodes.defaultMaterial_5.geometry} material={materials.Helmet_42} />
          <mesh geometry={nodes.defaultMaterial_6.geometry} material={materials.Helmet_42} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/viking.glb')
