/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/Hand.gltf
Author: scribbletoad (https://sketchfab.com/scribbletoad)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hand-low-poly-d6c802a74a174c8c805deb20186d1877
Title: Hand (low poly)
*/

import React, { useEffect, useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
let count=0
export function Hand(props) {
  const ref = useRef();
  const colorArray  = ['#3C486B','##FC7300','#F9F54B','#F45050' ,'#205E61'  ]


  
  function handleChange(event) {
    console.log('b',count)
    // Here, we invoke the callback with the new value
    if(count < 5){
      props.onChange(colorArray[count]);
      count= count+1
    }else{
      count =0
    }
    console.log('a',count)


  }
  const { nodes, materials } = useGLTF("./models/Hand.gltf");
  return (
    <group {...props} dispose={null}>
      <group position={[0.01, 470.41, -15.56]}>
        <mesh position={[0, 4.5, -10]}></mesh>
        <mesh
          ref={ref}
          onClick={handleChange}
          geometry={nodes.Object_5.geometry}
          material={materials.Material_46}
          position={[-44.8, 340.08, 35.91]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/Hand.gltf");
